# Generated by Django 4.2.7 on 2025-12-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_dish_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='table',
            name='table_seats_positive',
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(check=models.Q(('seats__gt', 0), ('seats__lte', 4)), name='table_seats_between_1_and_4'),
        ),
    ]
