# Generated by Django 4.2.7 on 2025-12-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_table_table_seats_positive_and_more'),
    ]

    operations = [
    ]
