# Generated by Django 4.2.7 on 2025-12-30 09:12
# This migration was broken and is now empty - will be handled in 0008

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20251230_0218'),
    ]

    operations = [
        # Empty migration - broken operations removed, will be handled in 0008
    ]
