# Generated by Django 4.2.7 on 2026-01-11 20:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0008_replace_client_with_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('preparing', 'Готовится'), ('ready', 'Готов к выдаче'), ('completed', 'Выдан'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Время получения')),
            ],
            options={
                'verbose_name': 'Заказ на вынос',
                'verbose_name_plural': 'Заказы на вынос',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TakeoutOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Позиция заказа на вынос',
                'verbose_name_plural': 'Позиции заказов на вынос',
                'ordering': ['dish__name'],
            },
        ),
        # Проблемные операции с индексами пропущены, так как индексы не существуют
        # migrations.RemoveIndex(
        #     model_name='reservation',
        #     name='bookings_re_client__123456_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='reservation',
        #     new_name='bookings_re_table_i_a5cedf_idx',
        #     old_name='bookings_re_table_i_123456_idx',
        # ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user'], name='bookings_re_user_id_9fa8d8_idx'),
        ),
        migrations.AddField(
            model_name='takeoutorderitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeout_order_items', to='bookings.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='takeoutorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.takeoutorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='takeoutorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeout_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='takeoutorderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='takeout_order_item_quantity_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='takeoutorderitem',
            unique_together={('order', 'dish')},
        ),
    ]
