# Generated by Django 3.2.25 on 2026-03-28 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_news_complaints_reviews_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order_subtotal',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Сумма заказа до скидки',
            ),
        ),
        migrations.AddField(
            model_name='reservation',
            name='order_total',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Итого к оплате',
            ),
        ),
    ]
