# Generated by Django 3.2.25 on 2026-04-22 20:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0014_reservation_applied_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('dine_in', 'Dine in'), ('takeout', 'Takeout')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer order',
                'verbose_name_plural': 'Customer orders',
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAppliedPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name_snapshot', models.CharField(max_length=255)),
                ('discount_amount_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Order applied promotion',
                'verbose_name_plural': 'Order applied promotions',
                'ordering': ['promotion_name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name_snapshot', models.CharField(max_length=255)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total_snapshot', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order item review',
                'verbose_name_plural': 'Order item reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionDishRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_role', models.CharField(choices=[('required', 'Required'), ('target', 'Target')], max_length=20)),
                ('min_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Promotion dish rule',
                'verbose_name_plural': 'Promotion dish rules',
                'ordering': ['sort_order', 'dish__name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly menu',
                'verbose_name_plural': 'Weekly menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Weekly menu day',
                'verbose_name_plural': 'Weekly menu days',
                'ordering': ['weekly_menu__name', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenuDayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Weekly menu day item',
                'verbose_name_plural': 'Weekly menu day items',
                'ordering': ['sort_order', 'dish__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dish review', 'verbose_name_plural': 'Dish reviews'},
        ),
        migrations.AlterModelOptions(
            name='menuoverride',
            options={'ordering': ['-priority', '-date_from', '-id'], 'verbose_name': 'Menu override', 'verbose_name_plural': 'Menu overrides'},
        ),
        migrations.AlterModelOptions(
            name='menuoverrideitem',
            options={'ordering': ['order', 'dish__name'], 'verbose_name': 'Menu override item', 'verbose_name_plural': 'Menu override items'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='promotioncomboitem',
            options={'ordering': ['promotion', 'dish__name'], 'verbose_name': 'Promotion combo item', 'verbose_name_plural': 'Promotion combo items'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='reservationappliedpromotion',
            options={'ordering': ['promotion__name'], 'verbose_name': 'Applied reservation promotion', 'verbose_name_plural': 'Applied reservation promotions'},
        ),
        migrations.AlterModelOptions(
            name='reservationdish',
            options={'ordering': ['dish__name'], 'verbose_name': 'Reservation line', 'verbose_name_plural': 'Reservation lines'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_number'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AlterModelOptions(
            name='venuecomplaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venue complaint', 'verbose_name_plural': 'Venue complaints'},
        ),
        migrations.AlterModelOptions(
            name='weeklymenudaysettings',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Weekly menu day settings', 'verbose_name_plural': 'Weekly menu day settings'},
        ),
        migrations.AlterModelOptions(
            name='weeklymenuitem',
            options={'ordering': ['order', 'dish__name'], 'verbose_name': 'Weekly menu item', 'verbose_name_plural': 'Weekly menu items'},
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='bookings_re_table_i_123456_idx',
        ),
        migrations.AddField(
            model_name='menuoverride',
            name='override_mode',
            field=models.CharField(choices=[('patch', 'Patch'), ('replace', 'Replace')], default='patch', max_length=20),
        ),
        migrations.AddField(
            model_name='menuoverride',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.dish'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='reservation_dish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.reservationdish'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menuoverride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menuoverride',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='menuoverride',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuoverride',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuoverride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menuoverrideitem',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], default='add', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuoverrideitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_override_items', to='bookings.dish'),
        ),
        migrations.AlterField(
            model_name='menuoverrideitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuoverrideitem',
            name='override',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.menuoverride'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed_off', 'Fixed off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Percent (0-100) or a fixed amount depending on discount type.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='kind',
            field=models.CharField(choices=[('single_dish', 'Single dish'), ('combo', 'Combo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='target_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_promotions', to='bookings.dish'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='valid_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotioncomboitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_combo_entries', to='bookings.dish'),
        ),
        migrations.AlterField(
            model_name='promotioncomboitem',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='promotioncomboitem',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='bookings.promotion'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='applied_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='bookings.promotion'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='order_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='promotion_discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.table'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationappliedpromotion',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservationappliedpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_applied_rows', to='bookings.promotion'),
        ),
        migrations.AlterField(
            model_name='reservationappliedpromotion',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promotion_links', to='bookings.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_dishes', to='bookings.dish'),
        ),
        migrations.AlterField(
            model_name='reservationdish',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservationdish',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='bookings.reservation'),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('operator', 'Operator'), ('admin', 'Admin')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='venuecomplaint',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venuecomplaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='venuecomplaint',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venuecomplaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklymenudaysettings',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True),
        ),
        migrations.AlterField(
            model_name='weeklymenudaysettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='weeklymenuitem',
            name='day_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.weeklymenudaysettings'),
        ),
        migrations.AlterField(
            model_name='weeklymenuitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_menu_items', to='bookings.dish'),
        ),
        migrations.AlterField(
            model_name='weeklymenuitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_published', '-published_at'], name='bookings_ne_is_publ_d7ba56_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['table', 'start_time', 'end_time'], name='bookings_re_table_i_a5cedf_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuoverride',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 0)), name='menu_override_priority_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuoverride',
            constraint=models.CheckConstraint(check=models.Q(('date_to__isnull', True), ('date_to__gte', django.db.models.expressions.F('date_from')), _connector='OR'), name='menu_override_date_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__gt', django.db.models.expressions.F('valid_from'))), name='promotion_valid_to_after_valid_from'),
        ),
        migrations.AddField(
            model_name='weeklymenudayitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_menu_day_items', to='bookings.dish'),
        ),
        migrations.AddField(
            model_name='weeklymenudayitem',
            name='weekly_menu_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.weeklymenuday'),
        ),
        migrations.AddField(
            model_name='weeklymenuday',
            name='weekly_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='bookings.weeklymenu'),
        ),
        migrations.AddField(
            model_name='promotiondishrule',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='bookings.dish'),
        ),
        migrations.AddField(
            model_name='promotiondishrule',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_rules', to='bookings.promotion'),
        ),
        migrations.AddField(
            model_name='orderitemreview',
            name='legacy_dish_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_review_projection', to='bookings.dishreview'),
        ),
        migrations.AddField(
            model_name='orderitemreview',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='bookings.dish'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='legacy_reservation_dish',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_projection', to='bookings.reservationdish'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.customerorder'),
        ),
        migrations.AddField(
            model_name='orderappliedpromotion',
            name='legacy_applied_promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_applied_promotion_projection', to='bookings.reservationappliedpromotion'),
        ),
        migrations.AddField(
            model_name='orderappliedpromotion',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promotions', to='bookings.customerorder'),
        ),
        migrations.AddField(
            model_name='orderappliedpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_applied_rows', to='bookings.promotion'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='legacy_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_projection', to='bookings.reservation'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='legacy_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_projection', to='bookings.reservation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.table'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuoverride',
            name='weekly_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='bookings.weeklymenu'),
        ),
        migrations.AddField(
            model_name='venuecomplaint',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='venuecomplaint',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='bookings.customerorder'),
        ),
        migrations.AddConstraint(
            model_name='weeklymenudayitem',
            constraint=models.UniqueConstraint(fields=('weekly_menu_day', 'dish'), name='weekly_menu_day_item_unique_dish'),
        ),
        migrations.AddConstraint(
            model_name='weeklymenuday',
            constraint=models.UniqueConstraint(fields=('weekly_menu', 'day_of_week'), name='weekly_menu_day_unique_per_menu'),
        ),
        migrations.AddConstraint(
            model_name='promotiondishrule',
            constraint=models.UniqueConstraint(fields=('promotion', 'dish', 'rule_role'), name='promotion_rule_unique_role_per_dish'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderappliedpromotion',
            constraint=models.UniqueConstraint(fields=('order', 'promotion'), name='order_applied_promotion_unique_per_order'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['user', 'scheduled_for'], name='bookings_cu_user_id_f21981_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['status', 'scheduled_for'], name='bookings_cu_status_9c5f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.CheckConstraint(check=models.Q(('subtotal_amount__gte', 0)), name='customer_order_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.CheckConstraint(check=models.Q(('discount_total__gte', 0)), name='customer_order_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='customer_order_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['table', 'start_time', 'end_time'], name='bookings_bo_table_i_5d4382_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'start_time'], name='bookings_bo_user_id_7b21ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', django.db.models.expressions.F('start_time'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('guests_count__gt', 0)), name='booking_guests_positive'),
        ),
    ]
