# Generated by Django 3.2.25 on 2026-04-26 15:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0020_auto_20260424_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(choices=[('none', 'Без авторизации'), ('bearer', 'Bearer token'), ('api_key', 'API key')], default='none', max_length=20)),
                ('secret_token', models.CharField(blank=True, max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_check_success', models.BooleanField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External integration',
                'verbose_name_plural': 'External integrations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Login attempt',
                'verbose_name_plural': 'Login attempts',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_failed_login_attempts', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('login_lockout_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('lockout_enabled', models.BooleanField(default=True)),
                ('force_password_change_after_admin_reset', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security settings',
                'verbose_name_plural': 'Security settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceDurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service duration option',
                'verbose_name_plural': 'Service duration options',
                'ordering': ['sort_order', 'duration_minutes'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSlotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_lead_time_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_working_days_ahead', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('slot_step_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service slot settings',
                'verbose_name_plural': 'Service slot settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceWeekdayWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True)),
                ('open_time', models.TimeField(default='12:00')),
                ('close_time', models.TimeField(default='22:30')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Service weekday window',
                'verbose_name_plural': 'Service weekday windows',
                'ordering': ['weekday'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('operator', 'Оператор'), ('admin', 'Администратор')], default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='BackupArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='backups/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_restored_at', models.DateTimeField(blank=True, null=True)),
                ('restore_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backup_archives', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_backup_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup archive',
                'verbose_name_plural': 'Backup archives',
                'ordering': ['-created_at'],
            },
        ),
    ]
